### ISSUE TITLE
Show specific line recommendations occur on

### ISSUE THREAD

**Issue by bengreenbank** [putyourlightson/craft-blitz-recommendations#7]
### Is your feature request related to a problem? Please describe.
The base Craft deprecation warnings show the line that the errors occur on, which can make it slightly easier to debug issues on larger templates. 

### Describe the solution you would like
This plugin to show the line that recommendations occur on in each template.

### Describe alternatives you have considered
Manually searching for all uses of a variable/asset in a template to find the recommendation that needs actioning. 

### Additional context
Deprecation warnings show the line they occur on (line 5 for example):
![Screenshot 2021-11-26 at 15 36 20](https://user-images.githubusercontent.com/61185468/143603898-96bd84c1-950e-4a29-a5d9-b3ad03772556.png)

**Comment by bencroker** [comment]
I agree that this would be a nice-to-have. However, due to how eager-loading opportunities are determined (by interpreting element queries), it is not trivial to narrow the origin down to a specific line number in the template. If this ever changes in future then we'll be sure to consider adding it, thanks for the suggestion!

**Comment by bencroker** [comment]
I managed to add this functionality in version 2.0.0.

**Comment by bengreenbank** [comment]
Great news, thanks very much!
